version: '3.8'
services:
    web:
        build:
            context: ../..
            dockerfile: docker/development/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ../..:/app
            - /app/node_modules
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/cv_website
            - NEXTAUTH_URL=http://localhost:3000
            - NEXTAUTH_SECRET=your-secret-key
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ov_website
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: