services:
    web:
        build:
            context: ./
            dockerfile: docker/Dockerfile.prod
        networks:
            - webapp
            - internal
        labels:
            - "traefik.enable=true"
            # Nastavení základního routeru
            - "traefik.http.routers.nextjs.rule=Host(`vase-domena.cz`)"
            - "traefik.http.routers.nextjs.entrypoints=websecure"
            # Nastavení TLS
            - "traefik.http.routers.nextjs.tls=true"
            - "traefik.http.routers.nextjs.tls.certresolver=letsencrypt"
            # Nastavení služby a portu
            - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
            - NEXTAUTH_URL=${NEXT_PUBLIC_BASE_URL}
            - PUPPETEER_URL=${PUPPETEER_URL}
        depends_on:
            - db
        restart: unless-stopped
        ports:
            -   "3000:3000"

    db:
        image: postgres:15-alpine
        networks:
            - internal
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ov_website
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./storage/postgresql/data:/var/lib/postgresql/data
        restart: unless-stopped

networks:
    webapp:
    internal: