version: '3.8'
services:
    web:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/app
            - node_modules:/app/node_modules:rw
            - /app/.next
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ov_website
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./storage/postgresql/data:/var/lib/postgresql/data
            - ./extras/sqls:/data

volumes:
    node_modules: