version: '3.8'
services:
    web:
        build:
            context: ./
            dockerfile: docker/development/Dockerfile
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ov_website
        volumes:
            - ov_postgres_data:/var/lib/postgresql/data

volumes:
    ov_postgres_data: