services:
    web:
        build:
            context: ./
            dockerfile: docker/Dockerfile.prod
        image: votava.dev:latest
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - NEXT_PUBLIC_BASE_URL=${APP_URL}
            - NEXTAUTH_URL=${APP_URL}
            - PUPPETEER_URL=http://web:3000
        labels:
            # Middleware pro přesměrování z www.votava.dev na ondra.votava.dev
            - 'traefik.http.middlewares.redirect-www-to-ondra.redirectregex.regex=^https?://www\.votava\.dev(.*)'
            - 'traefik.http.middlewares.redirect-www-to-ondra.redirectregex.replacement=https://ondra.votava.dev$1'
            - 'traefik.http.middlewares.redirect-www-to-ondra.redirectregex.permanent=true'

            # Middleware pro přesměrování z votava.dev na ondra.votava.dev
            - 'traefik.http.middlewares.redirect-apex-to-ondra.redirectregex.regex=^https?://votava\.dev(.*)'
            - 'traefik.http.middlewares.redirect-apex-to-ondra.redirectregex.replacement=https://ondra.votava.dev$1'
            - 'traefik.http.middlewares.redirect-apex-to-ondra.redirectregex.permanent=true'

            # Nastavení routeru pro www doménu s použitím middleware
            - 'traefik.http.routers.www-router.rule=Host(`www.votava.dev`)'
            - 'traefik.http.routers.www-router.middlewares=redirect-www-to-ondra'
            - 'traefik.http.routers.www-router.entrypoints=websecure'
            - 'traefik.http.routers.www-router.tls=true'

            # Nastavení routeru pro apex doménu s použitím middleware
            - 'traefik.http.routers.apex-router.rule=Host(`votava.dev`)'
            - 'traefik.http.routers.apex-router.middlewares=redirect-apex-to-ondra'
            - 'traefik.http.routers.apex-router.entrypoints=websecure'
            - 'traefik.http.routers.apex-router.tls=true'
        depends_on:
            - db
        restart: unless-stopped

    db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=ov_website
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./storage/postgresql/data:/var/lib/postgresql/data
        restart: unless-stopped