name: Build and Deploy to Coolify

on:
    push:
        branches:
            - main
        tags: [ 'v*.*.*' ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout kódu
                uses: actions/checkout@v4

            -   name: Nastavení Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Přihlášení k privátnímu registru
                uses: docker/login-action@v3
                with:
                    registry: registry.votava.dev
                    username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
                    password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: registry.votava.dev/votavadev/votava.dev
                    tags: |
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ./docker/Dockerfile.app
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    build-args: |
                        NODE_ENV=production
                    cache-from: type=registry,ref=registry.votava.dev/votavadev/votava.dev:buildcache
                    cache-to: type=registry,ref=registry.votava.dev/votavadev/votava.dev:buildcache,mode=max
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Spuštění deploye na Coolify
              run: |
                  curl -X POST -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}" \
                       ${{ COOLIFY_WEBHOOK_URL }}
